spring:
  application:
    name: citronix

  datasource:
    url: jdbc:postgresql://localhost:5432/citronix
    username: root
    password: ;(.314Luiv./
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
